let promptList = ["13th",
    "Abandoned Building",
    "ABC’s of Death",
    "ACAB",
    "Accordion Arms & Legs",
    "Acorn Friend",
    "Alien Encounter",
    "Air Conditioning",
    "Across the Street",
    "Alien Ghost",
    "Alone",
    "Amigara",
    "Amusement Park",
    "Analog Horror",
    "Antique Shop",
    "Apocalypse",
    "Apple Orchard",
    "Apple Picking",
    "Apple Pie",
    "At the Arcade",
    "Atop the Tallest Tree",
    "Autumn Trees",
    "Babysitter",
    "Backyard Camping",
    "Bad Moon on the Rise",
    "Bad Ritual",
    "Baking",
    "Ball Pit",
    "Based On A True Story",
    "Bats",
    "Bedsheet Ghost",
    "Bees",
    "Behind You",
    "BE NOT AFRAID",
    "Bigfoot",
    "Bigfoot Family Reunion",
    "Bike Ride",
    "Birds With Teeth",
    "Black Cat Appreciation Day",
    "Black Goat",
    "Blackout",
    "Blood",
    "Bloody Mary",
    "Body Horror",
    "Boo!",
    "The Boys Are Back In Town",
    "Brain Rot",
    "Brainless",
    "Breakfast",
    "Breaking News!",
    "Bridge",
    "Bricked Up",
    "Bug Bites",
    "Bugbear",
    "Buried Alive",
    "Burglar",
    "Burned",
    "Bus Stop",
    "Butler/Maid",
    "Butterflies",
    "Button-Eyed Scarecrow",
    "By the Lakeside",
    "Cabins",
    "Caffeine BOO-st",
    "Came Back Wrong",
    "Camp Counselor",
    "Campfire Story",
    "Candles",
    "Candy",
    "Candy Corn",
    "Candy Gore",
    "Candy Trade",
    "Cannibal",
    "Canoeing on the Lake",
    "Catching Fireflies",
    "Caught on Camera",
    "Childhood Monster",
    "Clown",
    "Cobwebs",
    "Color Out Of Space",
    "Conspiracy Board",
    "Conspiracy Theory",
    "Convenience Store",
    "Corn Maze",
    "Corpse",
    "Cosmic Horror",
    "The Country Fair",
    "Coven",
    "Creatures in the Tidepools",
    "Creek Monster",
    "Creep in the Window",
    "Creepy Crawly Bugs",
    "Creepy Dolls",
    "Creepy Little Girl",
    "Creepy Music",
    "Creepy Pastas",
    "Crooked Man",
    "Cryptids on the Beach",
    "Crystals",
    "Cursed Play",
    "Cursed Phone Number",
    "Dark Waters",
    "Dead as a Doornail",
    "Deal with the Devil",
    "Deep in the Forest",
    "Deep Underground",
    "Demented Kids Show",
    "Demons",
    "Detective",
    "Detention",
    "Devil on your Shoulder",
    "Diner",
    "Disco Aliens",
    "Dogs don't cry",
    "Don't get into stranger's vans",
    "Don't go in the basement",
    "Doppelgänger",
    "Drifter",
    "Drive-in Movie",
    "Early In the Morning",
    "Early Snow",
    "Ecentric Neighbors",
    "Eclipse",
    "Ectoplasm",
    "The Egg is Hatching",
    "Elevator to Hell",
    "Emo, Goth or Punk",
    "Everyone is Staring at me",
    "The Evil Eye",
    "Evil Laugh",
    "Eyeless",
    "Eyes",
    "Faceless",
    "Fairy",
    "Fall Apart",
    "Fall in Love",
    "Fall Fairytale",
    "Fall Gods",
    "Fall Pride",
    "Family Barbecue",
    "Family Business",
    "Family Reunion",
    "Famous Painting Halloween Redraw",
    "Farm",
    "Farmer’s Market",
    "Fashionable Werewolf",
    "Fetch With A Werewolf",
    "Final Girl",
    "Finding Firewood",
    "Fire Danger",
    "Fireworks",
    "Firewatch Tower",
    "Flatwoods Monster",
    "Flower Crown",
    "Fog",
    "Football",
    "Foot Prints",
    "Forbidden Knowledge",
    "Foreign Monsters",
    "Forever Sale",
    "Fortune Teller",
    "Found Footage",
    "Fox",
    "Frankenstein’s Monster",
    "Freak Show",
    "Frog Boy",
    "Front Door",
    "Fun House",
    "Garden",
    "Gargoyle",
    "Gas Station",
    "Gate",
    "Geocaching",
    "Ghost Bustin",
    "Ghost Hunting",
    "Ghost in the Machine",
    "Ghost Ship",
    "Ghost Town",
    "Ghostly Waltz",
    "Girl & Her Doll",
    "Give Me Something Good To Eat!",
    "Glaring of Cats",
    "Glow in the Dark",
    "Goatman",
    "Gone Fishing",
    "Goths in Summer",
    "Graffiti",
    "Grave Digger",
    "Grave Robber at Large",
    "Graveyard",
    "Graveyard Shift",
    "Grim Reaper",
    "Halloween Costume",
    "Halloween Decor",
    "Halloween Nostalgia",
    "Halloween OC",
    "Halloween Parade",
    "Hanging Out",
    "Haunted Hayride",
    "Haunted House",
    "Haunted Painting",
    "Haunted Video Game",
    "He's in the house!",
    "Headless",
    "Headless Horseman",
    "Hedge Maze",
    "Hermit Crabs",
    "Hexes and Curses",
    "Hibernation",
    "Hickies",
    "Hidden Corpse Found",
    "Hide n Seek Champion",
    "Hiding in the Walls",
    "Hiking Trail",
    "Hitchhiker",
    "Hoax",
    "Hocus Pocus",
    "Hocus, The Wandering Witch Hat",
    "Hollow",
    "Horns",
    "Horror Hotel",
    "Horror Movie Marathon",
    "Horror Movie Monster",
    "Horror Show Host",
    "Hospital",
    "How To Make an Angel",
    "Howl at the Moon",
    "Ice Scream Truck",
    "I didn't think mermaids would look like this",
    "I Figured out why this place closed down",
    "Impossible Geometries",
    "Inaccurate Animal Skeletons",
    "Infection",
    "Infestation",
    "In the Mirror",
    "Invader",
    "Is that racoon getting in the trash again?",
    "It was a dark and stormy night!",
    "It was an accident",
    "It’s Alive!",
    "Jack-in-the-Box",
    "Janitor",
    "Join the Cult",
    "Jump Scare",
    "Killer",
    "Killer’s Mugshot",
    "Kiss Me",
    "Labyrinthian Mall",
    "Lady in the Fields",
    "Lake Without a Reflection",
    "Lantern",
    "Lantern Light",
    "Lanyard",
    "Last Day of Summer",
    "Late Night Snack",
    "Leaf Pile",
    "Lesser Known Monster",
    "Library",
    "Lifeguard",
    "Lighthouse",
    "Liminal Space",
    "Little Jersey Devil",
    "Little Ol’ Lady",
    "The Local Scout Troop",
    "Long Teeth",
    "Lost Hiker",
    "Lost in the Woods",
    "Love At First Sight",
    "Love Sickness",
    "Lovecraftian",
    "Lucky",
    "Lumberjack",
    "Lure",
    "Make A Face",
    "Man-Eating Plant",
    "Mandrake",
    "Mascot Costume",
    "Mask Section",
    "Masked Monster",
    "Mausoleum",
    "Mayor",
    "Mechanical",
    "Melting",
    "Memento Mori",
    "Minotaur",
    "Mischief of Rats",
    "Miss Fall",
    "Missing Person Found",
    "Missing Person on a Milk Carton",
    "Missing Posters",
    "Monsters at the Mall",
    "Monster Dinner Party",
    "Monster in the Closet",
    "Monster Under the Bed",
    "Monstrous Mutation",
    "Moon Man",
    "Moonstruck",
    "Mosquitos",
    "Mothman",
    "Moths",
    "Moth Wings",
    "Mr. Pumpkin Head",
    "Multi-Headed",
    "Murder Mystery",
    "Murder of Crows",
    "Museum of Unnatural History",
    "Mushroom Circle",
    "Mushrooms",
    "Neighborhood Watch",
    "Nervous System",
    "Never go off the Trail",
    "New Ghoul At School",
    "Newcomer",
    "Night Owl",
    "Nightmares",
    "Notebook",
    "Nuclear Boy Scout",
    "An Odd Artifact",
    "Old Cartoons",
    "The Old Rusty Bunker",
    "An Ordinary Church",
    "Ouija Board",
    "Out on the Lake",
    "Outskirts of Town",
    "Overgrown",
    "Pack of Wolves",
    "Painting",
    "Parade of Pumpkins",
    "Party",
    "Party Games",
    "Peek",
    "Pet Cemetery",
    "Petroglyphs",
    "Phantom of the Opera",
    "Phobias",
    "Pickup Truck",
    "Pirate Costume",
    "Pizza Delivery to Nowhere",
    "Plague Doctor",
    "Playground",
    "Pocus, The Clumsy Caldron",
    "Podcast",
    "Poison Caramel Apple",
    "Poison Ivy",
    "Police Station",
    "Poltergeist Prankster",
    "Poolside",
    "Possession",
    "Potion Making",
    "Prank",
    "Preacher",
    "Princess Costume",
    "Prize Winning Pumpkin",
    "The Projectionist",
    "Prom Night",
    "Pumpkin Carving",
    "Pumpkin Knight",
    "Pumpkin Lollipop",
    "Pumpkin Patch",
    "Pumpkin Spice",
    "Randonauting",
    "Rake",
    "Rat King",
    "Reach",
    "Richest Man in Town",
    "Roadkill",
    "Roller Rink",
    "Roses",
    "S'mores",
    "A Sacrifice",
    "Sandbox",
    "Saturday Morning Cartoons",
    "Sawmill",
    "Scaredy Cat",
    "Scary or Cute?",
    "Science Experiment",
    "Screen Door",
    "Secret Lair",
    "Secret Passage",
    "Security Camera",
    "Severed Limb",
    "Sewer Gator",
    "Sexy Costume",
    "Shadow",
    "Sharp Teeth",
    "Show n' Tell",
    "Shut-in",
    "Silent Stalker",
    "Skelephones",
    "Skeleton",
    "Skeleton in the Closet",
    "Skull",
    "Skullmoth",
    "Sleepover",
    "Slenderman",
    "Slip n' Slide",
    "Smile Dog",
    "Snake",
    "Snakeskin",
    "Something on the Roof",
    "Something pretending to be Human",
    "Song Title (choose a song that makes you think of fall or halloween)",
    "Spell Book",
    "Spiders",
    "Spiders Apartment",
    "Spidolls",
    "Spirals",
    "Spirit Box",
    "Spooky Sapphics",
    "Stabbing",
    "Staircase",
    "Stalker With A Crush",
    "Star-crossed Lovers",
    "Star Gazing",
    "Strange Moon",
    "Strange Small Town",
    "Strange Superstition",
    "Strange Tunnel",
    "Stripes",
    "Sugar Fiends",
    "Summer Camp",
    "Sunburn",
    "Superhero Costume",
    "Susurrus",
    "Swamp",
    "Sweater Weather",
    "Sweet Insides",
    "Teenagers",
    "Tent",
    "Terrible Luck",
    "Tether Ball",
    "Thalassophobia",
    "Thatcher Effect",
    "That's not a deer",
    "Thing from my Nightmare",
    "Thing in the Moon",
    "Tire Swing",
    "Toilet Papering Prank",
    "Tourist Trap",
    "The Town at Night",
    "Town Square",
    "Toxic",
    "Trailer Park",
    "Train",
    "Trampoline",
    "Transformation",
    "Tree House",
    "Trick or Treat",
    "Troll",
    "True Crime",
    "Trypophobia",
    "TV at 3 A.M.",
    "The Undead",
    "Undead Wedding",
    "Under the Blankets",
    "Under the Floorboards",
    "Undercover Corpse",
    "Underworld",
    "Uninvited Guest",
    "Up in the Attic",
    "Upset Stomach",
    "Uzumaki",
    "Van Helsing",
    "Vampire",
    "Vampire vs Werewolf",
    "Vandalism",
    "Very Deep Hole",
    "Vintage Halloween",
    "Walking down the road",
    "Wand",
    "Warning Signs",
    "Washed Ashore",
    "Waterslide",
    "Well",
    "What is the Neighbor Hiding?",
    "What's on TV?",
    "Where do you go when you die?",
    "Wicked Wind",
    "Wide Eyed",
    "The Wild Hunt",
    "Wildlife",
    "Witches First Flight",
    "Witches Gathering",
    "Witches Hat",
    "Witch’s Gaze",
    "Workout",
    "Yokai",
    "You're not going to believe what I found!",
    "Your Psychic Friend",
    "Zodiac",
    "Zoo"
]

function random(prompts) {
    let n = Math.floor(Math.random() * (prompts.length))
    console.log(n)
    document.getElementById("prompt").innerHTML=prompts[n]
}
